version: "3.9"

services:
  front:
    build: ./front
    container_name: front_container
    ports:
      - "5173:5173"
    volumes:
      - ./front:/front
      - /front/node_modules
    depends_on:
      - api
    env_file: .env  
    environment:
      - NODE_ENV=development
      - VITE_API_HOST=${API_HOST}
      - VITE_API_PORT=${API_PORT}

  api:
    build: ./api
    container_name: api_container
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    volumes:
      - ./api:/api
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    env_file: .env
    ports:
      - "3300:3306"                      # проброс порта на хост
    volumes:
      - db_data:/var/lib/mysql           # сохраняем данные между перезапусками

volumes:
  db_data:      